### ISSUE TITLE
Add description and link of what "HMR commons" is. (in readme)

### ISSUE THREAD

**Issue by MorganConrad** [sveltejs/svelte-hmr#10]
I'm getting tired of projects and websites that say "We do TLA" but never tell you what TLA stands for.

This would also attract users - once I looked it up this looks possibly useful.  :-)

**Comment by rixo** [comment]
What's TLA? ;)

The next sentence in the README is trying to explain the very point you're mentioning:

> This packages provides shared dependencies for implementing Svelte HMR in any bundler plugins.

Isn't the meaning clear from this? Can you phrase it in a better way?

I'm not a native English speaker, so I sometime struggle to find the good words to explain things...

Are you hot on docs writing? Are you interested in making better docs for the projects revolving around Svelte HMR? I can easily explain things to you, in chat for example, and you can explain it better for the rest of the world...

**Comment by MorganConrad** [comment]
TLA = "three letter acronym"

I would suggest that you simply change the first line of your readme to

"HMR (Hot Module Replacement) commons for Svelte 3"

and, ideally, provide a link to more info about what HMR is.

**Comment by rixo** [comment]
Oh yes, "HMR", I didn't even notice this one. It's become transparent to me. How did you even ended up here if you don't know what it is?

But OK thanks for the advice, I'll add the little precision next time I update the docs.

I'm not sure "Hot Module Replacement" is a lot more obvious than simply HMR on its own... However, I'm certainly not going to start writing about the general concept of HMR right now. I'm still late on the specific projects docs themselves, and this information cannot be found anywhere else until I write it down, so it's more important :-/

Well... Should I leave this issue open until I add the little explanation to the README?

**Comment by rixo** [comment]
@MorganConrad Following your suggestion, I've added a [explanation of HMR](https://github.com/rixo/svelte-hmr#whats-hmr-by-the-way) in the readme of this project. I figured it could be as useful to newcomers as to people already knowing searching for it, to better understand their tools. Would love your feedback on it.

**Comment by MorganConrad** [comment]
Nice job!

**Comment by rixo** [comment]
Thanks! Closing, then. Thanks for chiming in :)
