### ISSUE TITLE
svelte-hmr@0.11.2 does not reload page (acceptable is undefined)

### ISSUE THREAD

**Issue by wfisk** [sveltejs/svelte-hmr#21]
I had an issue today with Svite and svelte-hmr when the page was only showing changes when I manually reloaded the page.  In my application I had directly installled svelte-hmr.  The issue just occurs when I install svelte-hmr@0.11.2 and above.  The issue does not occur when I install svelte-hmr@0.11.2-1 or below.  

In my Svite application I can  remove svelte-hmr from the package.json since Svite has a dependency (indirectly) on svelte-hmr (0.10.1).  So my solution to this issue is to not directly install svelte-hmr in my application.

I tried to debug why this is causing a problem and got as far as seeing that _acceptable_ is undefined and therefore
in hot-api.js:72 _canAccept_ is false.  _acceptable_ is set by calling _isAcceptable()_ in function createMakeHot/makeHot but I don't think that this function is ever called.  

Tested with this default Svite application and svite@0.11.2
https://github.com/wfisk/hot

**Comment by rixo** [comment]
Thanks for reporting.

This is caused by a mismatch between the svelte-hmr pulled from Svite's dependencies (via rollup-plugin-svelte-hot, that is in normal deps, used for the code transform), and the svelte-hmr installed as a peer dependency.

I've reached out to @dominikg to find a proper solution.

**Comment by dominikg** [comment]
svite-0.8.1-beta.0 synchronized the version range selectors and works with latest svelte-hmr

**Comment by rixo** [comment]
OK cool so we are fixed here. Feel free to reopen if you still encounter this with Svite beta.0.
