### ISSUE TITLE
Add hot reload to imported SCSS files on SvelteKit

### ISSUE THREAD

**Issue by flayks** [sveltejs/svelte-hmr#22]
As we chatted about it on Discord, that would be very cool to have HMR on a global SCSS file for SvelteKit like that:

```svelte
// $layout.svelte
<style lang="scss" global>
    @import "../style/style.scss";
</style>
```

Right now it doesn't seem to hot reload the changes when changing an imported SCSS file.

**Comment by flayks** [comment]
Just for testing purposes, I've also put all the imports of my `style.scss` file directly into the `<style>`, but it doesn't seem to fix the issue, so I think it purely linked to imported SCSS files

```svelte
<!-- $layout.svelte or index.svelte (tried both) -->

<style lang="scss" global>
    // @import "../style/style.scss";

    // Dependencies
    @import "sanitize.css/sanitize";

    // Tools
    @import "../style/variables";
    @import "../style/tools/mixins";
    @import "../style/tools/functions";
    @import "../style/tools/helpers";

    // Base
    @import "../style/base";
    @import "../style/fonts";
    @import "../style/typography";

    // Layout
    @import "../style/layout/grid";
</style>
```

**Comment by rixo** [comment]
Thanks.

OK so after a few research, I think it's on its way to be fixed in `@snowpack/plugin-svelte`: https://github.com/snowpackjs/snowpack/pull/2109.

Now, this will only works if the imported files are also watched by Snowpack. AFAICT this means you'll ever have to move your `style` directory inside `src`, or add `style` to Snowpack's mounts.

Closing since the resolution will happen in `@snowpack/plugin-svelte`.

**Comment by FredKSchott** [comment]
Since the "dependencies" array that https://github.com/snowpackjs/snowpack/pull/2109 is relying on uses file paths, I *think* that PR will work regardless of whether the style dir is mounted and watched by Snowpack. I'll test it out to confirm though

**Comment by Easy-Cloud-in** [comment]
Svelte-Kit now use vite.js  for packing, how to use scss config in vite.js?

**Comment by LeonardoBrandao** [comment]
I got it working by importing the `svelte-preprocess` in the `svelte.config.cjs` file and using it like this:

```js
const sveltePreprocess = require('svelte-preprocess');
module.exports = {
	kit: {
		// other options
	},
	preprocess: sveltePreprocess()
};
```

**Comment by Easy-Cloud-in** [comment]
Thank you, Leonardo, I made it work. Please let me know how to use node_module libraries like locomotive-scroll work with svelte-kit.  how to config in vite.js?

**Comment by michapixel** [comment]
> 
> 
> I got it working by importing the `svelte-preprocess` in the `svelte.config.cjs` file and using it like this:
> 
> ```js
> const sveltePreprocess = require('svelte-preprocess');
> module.exports = {
> 	kit: {
> 		// other options
> 	},
> 	preprocess: sveltePreprocess()
> };
> ```

that doesn't fix the bug the OP mentioned. 
@imported file-changes are NOT hot reloaded atm. 

And to me that's a major issue, beceuse i like to have my styles inside different files.  I personally don't want to use those oversized css-frameworks anymore. i just don't need them 99% of the time. My (s)css  files are very small, but i like to have them seperated an esternal. If i have to write them directly into a component or the root /layout file i'd have to admit svelte-(kit) won't be any interesting anymore. 

I'm sorry if this is not the right place. I just wanted to emphasize the urgency i have with svelte@next

**Comment by raghav-kukreti** [comment]
Hey @michapixel I made it work by creating a `__layout.svelte` in my routes folder and scoping out the SCSS files in an import like:
```html
<svelte:head>
 <style lang="scss">
  @import '../global.scss';
 </style>
</svelte:head>
```
This is with the same config as yours, hopefully, it works for you.

**Comment by dominikg** [comment]
@raghav-kukreti  there are better ways to use/import global styles with vite. 

Also vite-plugin-svelte (and sveltekit that uses it) support hmr for changed dependencies of preprocessors, no need for awkward workarounds.
In general you should try to limit what you import in svelte style nodes, the scoped styles are for components and need to run through svelte-preprocess, there should not be any global styles in there.
