### ISSUE TITLE
Uncaught TypeError: Adapter is not a constructor

### ISSUE THREAD

**Issue by didierfranc** [sveltejs/svelte-hmr#27]
👋

I've got this issue when `"source": "remote"` is enabled in the snowpack config, the error comes from **svelte-hmr** but it may not be the guilty

<img width="1682" alt="Screenshot 2021-03-07 at 15 27 20" src="https://user-images.githubusercontent.com/14132464/110243271-f25e1100-7f59-11eb-9f97-d91c928ea145.png">

**To reproduce:**
- Bootstrap a svelte project with create-snowpack-app
```sh
npx create-snowpack-app test --template @snowpack/app-template-svelte-typescript
```
- Then add `source: "remote"` to `snowpack.config.js`

**Comment by rixo** [comment]
Oops, messed my tags on npm. `latest` was pointing to a broken prerelease. This should be fixed now. Sorry for the inconvenience. Thanks for reporting!

**Comment by didierfranc** [comment]
Thanks @rixo !

**Comment by nicknack23** [comment]
I got the exact same error today. Is there an easy way to fix this locally or do I have to wait for an npm update? (Sorry, but I'm a snowpack noob and don't really understand how it works yet.)

**Comment by nicknack23** [comment]
I'm not sure if you receive notifications for new comments in closed issues, so maybe it's best to page @rixo so you don't miss that there's a problem here.

**Comment by rixo** [comment]
@nicknack23 Hi! Are you using remote source too? Do you get this same error overlay? Does it mention the precise version of svelte-hmr that is pulled into your project, like the screenshot of the OP does?

**Comment by nicknack23** [comment]
Thanks for the quick response! Yes to remote source and same error overlay. Here's the text of mine:

```
Unhandled Runtime Error
Uncaught TypeError: Adapter is not a constructor

Source
http://localhost:8080/_snowpack/pkg/-/svelte-hmr@v0.13.0-GsmlFwQfqcvMNDNNRjs2/dist=es2020,mode=imports/unoptimized/runtime/proxy.js [:129:21]
TypeError: Adapter is not a constructor
    at new ProxyComponent (http://localhost:8080/_snowpack/pkg/-/svelte-hmr@v0.13.0-GsmlFwQfqcvMNDNNRjs2/dist=es2020,mode=imports/unoptimized/runtime/proxy.js:129:21)
    at new Proxy<TestProject> (http://localhost:8080/_snowpack/pkg/-/svelte-hmr@v0.13.0-GsmlFwQfqcvMNDNNRjs2/dist=es2020,mode=imports/unoptimized/runtime/proxy.js:212:11)
    at http://localhost:8080/dist/main.js:9:13
```

**Comment by rixo** [comment]
Err... So we're pulling the latest version of the `svelte-hmr` runtime in the browser, but using the [previous version](https://github.com/snowpackjs/snowpack/blob/a178f286ca46e79f7086370eb88ed038883081b6/plugins/plugin-svelte/package.json#L21) of the code transform in the Snowpack plugin. And they're not compatible.

This needs to be fixed by upgrading `svelte-hmr` version in the Snowpack plugin, and ensuring compatibility with the options that have changed. I'm trying to get back at this soon.

**Comment by nicknack23** [comment]
Great, thanks. I'll keep my eyes on this issue to see when you get a fix up.

**Comment by rixo** [comment]
This has been merged at Snowpack's so this should be fixed now. Anyone still encountering issues with this? (Comment here and I'll reopen if so.)
