### ISSUE TITLE
Trying to load files relative to root of machine

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/svelte-hmr#28]
Had an issue this morning where `hot-api-esm.js` and `proxy-adapter-dom.js` both started trying to load from the root of my hard drive rather than the dev website after installing updates (using SvelteKit / vite).

Tracked it down to the "/" added at the start of this:
https://github.com/rixo/svelte-hmr/blob/f41cefc8296dd32a172627b330f895bf196eacd7/index.js#L5

Sorry, completely unfamiliar with the package but removing the "/" made things work again.

To reproduce, just create a brand new project as per https://github.com/sveltejs/kit, then start dev mode - the two files above will probably fail to load and the app not function.

To fix, add `"svelte-hmr": "0.13.1"` to your package.json to use the previous version of this package.

**Comment by JoshuaJarman** [comment]
![image](https://user-images.githubusercontent.com/36280055/111700527-c31b8f80-87f6-11eb-905b-6fac9cdfb16e.png)
can confirm that i am seeing the same issue.

**Comment by frederikhors** [comment]
Maybe the same problem here https://github.com/rixo/rollup-plugin-svelte-hot/issues/19?

**Comment by CaptainCodeman** [comment]
Looks like it's been fixed someplace else, setup is working again this morning

**Comment by babeard** [comment]
looks like 7d04e6c60794da6e8bd7e49b8a2b10afb2bf26b8 fixed it!
