### ISSUE TITLE
Building with Webpack got the following error

### ISSUE THREAD

**Issue by joglomedia** [sveltejs/svelte-hmr#39]
Hi there,

I am not sure if this error related to Svelte or svelte-hmr. I try to build Svelte for Laravel using webpack (from laravel-mix), once I try to build it, got the following error:

```bash
WARNING in ./node_modules/.pnpm/svelte-hmr@0.14.7_svelte@3.29.0/node_modules/svelte-hmr/runtime/proxy-adapter-dom.js 7:21-52
export 'insert_hydration' (imported as 'svelteInternal') was not found in 'svelte/internal'
```

**Comment by rixo** [comment]
Yes, it's in svelte-hmr.

You shouldn't have HMR / dev mode enabled for build, though. Is that really what you meant, or do you also get this warning during dev?

Also, what version of Svelte are you using? Do you still get this warning with lastest Svelte?

**Comment by piptouque** [comment]
I had the same warning, updating Svelte to >3.40.0 fixed it (for some reason I had specified an earlier version of Svelte in my `package.json`). Thanks!

**Comment by joglomedia** [comment]
> I had the same warning, updating Svelte to >3.40.0 fixed it (for some reason I had specified an earlier version of Svelte in my `package.json`). Thanks!

I have follow your solution, upgrading my Svelte to 3.41, the previous error has gone... Thank you.
