### ISSUE TITLE
Exported functions become "stale" on hot reload

### ISSUE THREAD

**Issue by enyo** [sveltejs/svelte-hmr#43]
### Describe the bug

When a component exposes a function with `export const doStuff = () => { /* code */ }` so that an outer component can invoke it, the code inside the exported function doesn't have access to the local variables anymore after reload.

### Reproduction

https://svelte.dev/repl/5d2a100498f34c50ad9ce2ff2a4e3569?version=3.46.4

### System Info

```shell
macOS
```

### Severity

annoyance

**Comment by bluwy** [comment]
Duplicate of https://github.com/sveltejs/vite-plugin-svelte/issues/134

**Comment by enyo** [comment]
@bluwy are you sure it's the same? Mine has nothing to do with context module.

**Comment by bluwy** [comment]
Ah I think you're right. I can reproduce this too at https://stackblitz.com/edit/vitejs-vite-rdqnfu?file=src%2FInner.svelte&terminal=dev. Transferring this over to vite-plugin-svelte as HMR is not related to Svelte. But this issue could be related to svelte-hmr too.

Repro steps with stackblitz:

1. Start the dev server
2. Edit `Inner.svelte`
3. Click on the "Open" button
4. Notice that the "Open: false" text did not become "Open: true"

**Comment by dominikg** [comment]
i suppose this is one for svelte-hmr. cc @rixo

**Comment by rixo** [comment]
Yes, I confirm this is independent from the `context=module` issue, and that this is the responsibility of `svelte-hmr`. This one should be easier, since it pertains to component instances, where `svelte-hmr` is really acting.

Should we transfer the issue to `svelte-hmr` or create another one there?

**Comment by bluwy** [comment]
I don't have permissions to transfer over to svelte-hmr, unless someone does 👀 Else I'm fine recreating an issue there too.
