### ISSUE TITLE
ProxyComponent makes it impossible to check if something is a SvelteComponent (e.g. the class)

### ISSUE THREAD

**Issue by SystemParadox** [sveltejs/svelte-hmr#65]
If you have some code that accepts both a svelte component or a function, you can tell them apart with things like:

```
import { SvelteComponent } from 'svelte';
import Component from './Component.svelte';

// Option 1
!!Component.prototype instanceof SvelteComponent;

// Option 2
!!Component.prototype.$destroy;
```

However, when you've got svelte-hmr enabled then `ProxyComponent` gets in the way and neither of these work.

Please could `ProxyComponent` be changed in some way so that there is something we can do to tell between functions and components that will also work with svelte-hmr?

Thanks.

**Comment by rixo** [comment]
When HMR is active, the actual component is exposed as `proxy.$$.hmr_cmp`. This is not public API, but this is not going to change before Svelte 5.

So you could do something like this:

```js
const actualComponent = cmp.$$?.hmr_cmp ?? cmp

// then run the test you want to determine if actualComponent is a Svelte component or not
```

**Comment by Kabakuro** [comment]
Logging the `component` displays the class but `component.$$` seems to log `undefined` where we're trying to use this. We are currently locked to svelte version 3.55.1 for our project, is this why we're not getting anything from it?
