### ISSUE TITLE
Component gets created again and again when hot reload

### ISSUE THREAD

**Issue by juniorforlife** [sveltejs/svelte-hmr#74]
Hi I'm new to Svelte so I'm not sure if this is the right place to ask this problem. 
Basically I have a YoutubePlayer component as follow:
```
<script >
  import { onMount } from 'svelte';

  export let youtubePlayer: YouTubePlayer;
  export let videoId: string | undefined;
  export let playing = false;

  const playerId = crypto.randomUUID();

  $: {
    if (videoId && youtubePlayer && typeof youtubePlayer.loadVideoById === 'function') {
    youtubePlayer.loadVideoById(videoId);
    }
  }

  $: {
    if (youtubePlayer.playVideo &&
      youtubePlayer.pauseVideo
    ) {
      if (playing) {
        youtubePlayer.playVideo();
      } else {
        youtubePlayer.pauseVideo();
      }
    }
  }

  onMount(() => {
    console.log('MOUNT');
    function load() {
      youtubePlayer = new YT.Player(playerId, {
        videoId,
        playerVars: { autoplay: 1, mute: 1 },
      });
    }

    if (window.YT) {
      load();
    } else {
      // @ts-ignore
      window.onYouTubeIframeAPIReady = load;
    }
  });
</script>

<svelte:head>
  <script src="https://www.youtube.com/iframe_api"></script>
</svelte:head>

<div id={playerId} />
```
When I comment/uncomment this part and save the file..

```
$: {
    if (youtubePlayer.playVideo &&
      youtubePlayer.pauseVideo
    ) {
      if (playing) {
        youtubePlayer.playVideo();
      } else {
        youtubePlayer.pauseVideo();
      }
    }
}
```
... then `onMount` will be triggered again and a new instance of YoutubePlayer is created. 
Since I don't show/hide the component, I expect it to be not mounted again.

**Comment by dominikg** [comment]
you are changing the implementation of the component. Instances have to be recreated so that these changes are applied in the browser. It cannot retroactively change existing instances to do what the updated code says.

**Comment by juniorforlife** [comment]
But when I add a new state and a new div that uses that state then it doesn’t recreate the component. Why is that?

**Comment by rixo** [comment]
For the record, fully recreating modified components is indeed the basic principle of HMR. This means that existing instances of the impacted component are fully recreated, including running their complete lifecycle (`onDestroy`, `onMount`, etc.). This also implies that all the children of an impacted component instance are similarly fully recreated.

The only case where a component is not recreated is when the change impacts only the CSS (and the bundler, plugin, setup, etc. allows to detect and handle this special case correctly).
