### ISSUE TITLE
Svelte 5 compatibility

### ISSUE THREAD

**Issue by rmunn** [sveltejs/svelte-hmr#88]
When creating a new Svelte project with `pnpm create svelte` and choosing Svelte 5, `pnpm install` warns about unmet peer dependencies. svelte-hmr lists dependencies on `svelte@"^3.19.0 || ^4.0.0"`, but not Svelte 5.

If I ignore the error and proceed, everything seems to work as it should, but it would be nice if the svelte-hmr package explicitly listed Svelte 5 has a valid peer dependency.

**Comment by benmccann** [comment]
This package will not add support for Svelte 5 because HMR will be built directly into Svelte 5

**Comment by dominikg** [comment]
more info here https://github.com/sveltejs/svelte-hmr/pull/87

**Comment by rmunn** [comment]
I searched through issues but forgot to search PRs. Thanks for the link to #87.
