### ISSUE TITLE
svelte5 npm package unmatch version 

### ISSUE THREAD

**Issue by zhuzhuaicoding** [sveltejs/svelte-hmr#89]
├─┬ @sveltejs/vite-plugin-svelte 3.0.2
│ └─┬ svelte-hmr 0.15.3
│   └── ✕ unmet peer svelte@"^3.19.0 || ^4.0.0": found 5.0.0-next.48

**Comment by Aloso** [comment]
That might have something to do with HMR not yet being implemented for Svelte 5:

```
23:59:01 [vite-plugin-svelte] Your are using Svelte 5.0.0-next.79. Svelte 5 support is experimental, breaking changes can occur in any release until this notice is removed.
work in progress:
 - svelte-inspector is disabled until dev mode implements node to code mapping
 - hmr for .svelte files is disabled until hmr api is implemented
 ```

**Comment by dominikg** [comment]
yes, svelte5 is going to have built-in support for hmr, this package is only needed for svelte4
